version: '3.7'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .envdir/development/database
      - .envdir/development/web
    depends_on:
      - database
  
  database:
    image: postgres
    env_file:
      - .envdir/development/database

volumes:
  gem_cache:
